### ISSUE TITLE
ANTLR grammar

### ISSUE THREAD

**Issue by mwillema** [mwillema/protobuf-parser#1]
ANTLR 4 grammar from the [Protocol Buffers Version 3 Specification](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec).

The language specification has been respected as much as possible when writing the ANTLR 4 grammar. However I've discovered a couple of issues:

1. In String literals, I hardly understood `/[^\0\n\\]/`. So I wrote the ANTLR grammar rule `~[\0\n\\]`, meaning all characters but \0, \n and \\.

2. In Syntax, the rule `syntax = "syntax" "=" quote "proto3" quote ";"` is not correct. Indeed, the string `"proto3"` will be recognized as a string literal before being recognized as the token `"`, followed by `proto3` followed by `"` again. Also the rule as stated allows the following inputs: `"proto3'` and `'proto3"` which are refused by the Protobuf compiler.

3. In Fields, the end of rule `type = ... | messageType | enumType` is not correct, since the parser has no way to know the difference between a message type `messageType = [ "." ] { ident "." } messageName` and an enum type `enumType = [ "." ] { ident "." } enumName`. In my ANTLR grammar I fixed the problem by introducing a rule `messageOrEnumType`.

4. In Reserved, the `ranges` rule is not defined. I supposed the following definition (EBNF):
`ranges =  range ["," range]`
`range = IntLit | (IntLit "to" IntLit)`

5. In Service definition, the rule `stream` is not defined. However due to a lack of example I couldn't come up with a grammar rule.

When the ANTLR grammar diverges it is because of ANTLR features or best practices.

I have written unit tests that test the generated parser against the following .proto files:

- The example found at the end of the [language specification](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#proto_file)
- [addressbook.proto](https://github.com/google/protobuf/blob/master/examples/addressbook.proto)
- [conformance.proto](https://github.com/google/protobuf/blob/master/conformance/conformance.proto)

I posted a [message](https://groups.google.com/forum/#!topic/protobuf/_R8y2S0LvXc) on the Protobuf Forum to share my findings.

**Comment by anandolee** [comment]
Thanks for let us know these issues.
We may not change the first 3 issues. messageType and enumType for example, may better to human understand the usages.

For issue 4 and 5, I have fixed them in our internal code (not published yet). 

4:
ranges = range { "," range }
range =  intLit [ "to" ( intLit | "max" ) ]

5, stream is not supported in proto3, so:
service = "service" serviceName "{" { option | rpc | emptyStatement } "}"
